stages:
  - lint
  - codesniffer
  - unit

lint:lint-php5.4:
  stage: lint
  image: php:5.4
  before_script:
    - bash ci/docker_install-lint.sh > /dev/null
  script:
    - bash ci/phplint.sh ./

lint:lint-php5.6:
  stage: lint
  image: php:5.6
  before_script:
    - bash ci/docker_install-lint.sh > /dev/null
  script:
    - bash ci/phplint.sh ./

lint:lint-php7.0:
  stage: lint
  image: php:7.0
  before_script:
    - bash ci/docker_install-lint.sh > /dev/null
  script:
    - bash ci/phplint.sh ./

lint:lint-php7.1:
  stage: lint
  image: php:7.1
  before_script:
    - bash ci/docker_install-lint.sh > /dev/null
  script:
    - bash ci/phplint.sh ./

codesniffer:
  stage: codesniffer
  image: php:5.6
  before_script:
    - bash ci/docker_install-cs.sh > /dev/null
  script:
    - bash ci/phpcs.sh
  allow_failure: true

unit:testBasic:
  stage: unit
  image: php:5.6
  before_script:
    - bash ci/docker_install-unit.sh > /dev/null
  script:
    - bash ci/phpunitBasic.sh

unit:testRead:
  stage: unit
  image: php:5.6
  before_script:
    - bash ci/docker_install-unit.sh > /dev/null
  script:
    - bash ci/phpunitRead.sh

unit:testReadAssertFail:
  stage: unit
  image: php:5.6
  before_script:
    - bash ci/docker_install-unit.sh > /dev/null
  script:
    - bash ci/phpunitReadAssert.sh

unit:testPageProperty:
  stage: unit
  image: php:5.6
  before_script:
    - bash ci/docker_install-unit.sh > /dev/null
  script:
    - bash ci/phpunitPageProperty.sh	

unit:testUserProperty:
  stage: unit
  image: php:5.6
  before_script:
    - bash ci/docker_install-unit.sh > /dev/null
  script:
    - bash ci/phpunitUserProperty.sh